CREATE TABLE UTILISATEUR (
    ID_UTILISATEUR NUMBER PRIMARY KEY,
    NOM VARCHAR2(50),
    PRENOM VARCHAR2(50),
    EMAIL VARCHAR2(100) UNIQUE,
    ROLE VARCHAR2(20) CHECK (ROLE IN ('Admin', 'Professeur', 'Personnel Administratif', 'Étudiant')),
    ID_SITE NUMBER REFERENCES SITE(ID_SITE)
);

CREATE TABLE TECHNICIEN (
    ID_TECHNICIEN NUMBER PRIMARY KEY,
    NOM VARCHAR2(50),
    PRENOM VARCHAR2(50),
    ENTREPRISE VARCHAR2(100),
    COMPETENCES VARCHAR2(255), 
    HEURE_DEBUT_SERVICE TIMESTAMP,
    HEURE_FIN_SERVICE TIMESTAMP
);


CREATE TABLE SITE (
    ID_SITE NUMBER PRIMARY KEY,
    NOM VARCHAR2(50) UNIQUE
);

CREATE TABLE MATERIEL (
    ID_MATERIEL NUMBER PRIMARY KEY,
    TYPE_MATERIEL VARCHAR2(50),
    MODELE VARCHAR2(50),
    ETAT VARCHAR2(20) CHECK (ETAT IN ('Disponible', 'En panne', 'Réparé')),
    ADRESSE_IP VARCHAR2(15) UNIQUE, 
    QUANTITE NUMBER CHECK (QUANTITE >= 0),
    ID_SITE NUMBER REFERENCES SITE(ID_SITE)
);

CREATE TABLE INTERVENTION (
    ID_INTERVENTION NUMBER PRIMARY KEY,
    ID_MATERIEL NUMBER REFERENCES MATERIEL(ID_MATERIEL),
    ID_TECHNICIEN NUMBER REFERENCES TECHNICIEN(ID_TECHNICIEN),
    DATE_DEMANDE DATE DEFAULT SYSDATE,
    DATE_DEBUT DATE,  
    DATE_FIN DATE,  
    STATUT VARCHAR2(20) CHECK (STATUT IN ('En attente', 'En cours', 'Résolu')),
    DESCRIPTION VARCHAR2(255)
);

CREATE TABLE UTILISATION_MATERIEL (
    ID_UTILISATEUR NUMBER REFERENCES UTILISATEUR(ID_UTILISATEUR),
    ID_MATERIEL NUMBER REFERENCES MATERIEL(ID_MATERIEL),
    DATE_UTILISATION DATE DEFAULT SYSDATE,
    PRIMARY KEY (ID_UTILISATEUR, ID_MATERIEL, DATE_UTILISATION) 
);

/*
Utilisateur (idUtilisateur, nom, prenom, email, role, #idSite)  
Technicien (idTechnicien, competence, heure_debut_service, heure_fin_service)  
Site (idSite, nom)  
Materiel (idMateriel, type, modele, etat, adresse_ip, quantite, #idSite)  
Intervention (idIntervention, #idMateriel, #idTechnicien, date_demande, date_debut, date_fin, statut, description)  
Utilisation_Materiel (#idUtilisateur, #idMateriel, date)  
*/
