SHOW CON_NAME;
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CONTAINER = CDB$ROOT;

-- 7. Donner les quotas à C##CERGY
ALTER USER C##CERGY QUOTA UNLIMITED ON USERS;
ALTER USER C##CERGY QUOTA UNLIMITED ON ts_donnees;
ALTER USER C##CERGY QUOTA UNLIMITED ON ts_index;
ALTER USER C##CERGY QUOTA UNLIMITED ON ts_logs;
ALTER USER C##CERGY QUOTA UNLIMITED ON ts_site_cergy;
ALTER USER C##CERGY QUOTA UNLIMITED ON ts_site_pau;
