-- CREATION des TABLES
CREATE TABLE SITE (
    ID_SITE NUMBER PRIMARY KEY,
    NOM VARCHAR2(50) UNIQUE
) TABLESPACE ts_donnees;

CREATE TABLE UTILISATEUR (
    ID_UTILISATEUR NUMBER PRIMARY KEY,
    NOM VARCHAR2(50),
    PRENOM VARCHAR2(50),
    EMAIL VARCHAR2(100) UNIQUE,
    ROLE VARCHAR2(20) CHECK (ROLE IN ('Admin', 'Professeur', 'Personnel_Administratif', 'Etudiant')),
    ID_SITE NUMBER REFERENCES SITE(ID_SITE)
)CLUSTER cluster_utilisation_materiel (ID_UTILISATEUR);


CREATE TABLE MATERIEL (
    ID_MATERIEL NUMBER PRIMARY KEY,
    TYPE_MATERIEL VARCHAR2(50),
    MODELE VARCHAR2(50),
    ETAT VARCHAR2(20) CHECK (ETAT IN ('Disponible', 'En panne')),
    ADRESSE_IP VARCHAR2(15) UNIQUE, 
    QUANTITE NUMBER CHECK (QUANTITE >= 0),
    ID_SITE NUMBER REFERENCES SITE(ID_SITE)
) CLUSTER cluster_intervention_materiel (ID_MATERIEL);

CREATE TABLE UTILISATION_MATERIEL (
    ID_UTILISATEUR NUMBER,
    ID_MATERIEL NUMBER REFERENCES MATERIEL(ID_MATERIEL),
    DATE_UTILISATION DATE DEFAULT SYSDATE,
    PRIMARY KEY (ID_UTILISATEUR, ID_MATERIEL, DATE_UTILISATION)
) CLUSTER cluster_utilisation_materiel (ID_UTILISATEUR);

-- pour supprimer technicien, on drop intervention puis technicien

CREATE TABLE INTERVENTION (
    ID_INTERVENTION NUMBER PRIMARY KEY,
    ID_MATERIEL NUMBER,
    ID_TECHNICIEN NUMBER REFERENCES TECHNICIEN(ID_TECHNICIEN),
    DATE_DEMANDE DATE DEFAULT SYSDATE,
    DATE_DEBUT DATE,  
    DATE_FIN DATE,  
    STATUT VARCHAR2(20) CHECK (STATUT IN ('En attente', 'En cours', 'Résolu')),
    DESCRIPTION VARCHAR2(255)
) CLUSTER cluster_intervention_materiel (ID_MATERIEL);

CREATE TABLE TECHNICIEN (
    ID_TECHNICIEN NUMBER PRIMARY KEY,
    NOM VARCHAR2(50),
    PRENOM VARCHAR2(50),
    ENTREPRISE VARCHAR2(100),
    COMPETENCES VARCHAR2(255), 
    HEURE_DEBUT_SERVICE VARCHAR2(10),
    HEURE_FIN_SERVICE VARCHAR2(10),
    ID_SITE NUMBER REFERENCES SITE(ID_SITE)
)TABLESPACE ts_donnees;
